/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.view;

import com.tec02.API.JsonBodyAPI;
import com.tec02.common.Keyword;
import com.tec02.API.RequestParam;
import com.tec02.API.APIController;
import com.tec02.gui.frameGui.AbsDisplayAble;
import com.tec02.gui.frameGui.Component.PopupMenu;
import com.tec02.gui.panelGui.TableAndLocation;
import com.tec02.common.PropertiesModel;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ManagePc extends AbsDisplayAble {

    private final TableAndLocation tableAndLocation;
    private final APIController api;

    /**
     * Creates new form ManagePc
     */
    public ManagePc() {
        initComponents();
        this.api = APIController.getInstance();
        this.tableAndLocation = new TableAndLocation(api);
        this.tableAndLocation.setUrlAdd(PropertiesModel.getConfig(Keyword.Url.Pc.POST));
        this.tableAndLocation.setUrlGet(PropertiesModel.getConfig(Keyword.Url.Pc.GET));
        this.tableAndLocation.setUrlPut(PropertiesModel.getConfig(Keyword.Url.Pc.PUT));
        this.tableAndLocation.setUrlDelete(PropertiesModel.getConfig(Keyword.Url.Pc.DELETE));
        PopupMenu selectedMenu = this.tableAndLocation.getSelectedMenu();
        selectedMenu.addItemMenu("Delete", (e) -> {
            this.tableAndLocation.deleteSeleled();
        });
        selectedMenu.addItemMenu("Change Line", (e) -> {
            JComboBox<String> comboBox = new JComboBox<>();
            for (String lineItem : this.tableAndLocation.getLineItems()) {
                comboBox.addItem(lineItem);
            }
            Object[] components = {"Select an line:", comboBox};
            int result = JOptionPane.showOptionDialog(null, components, "Change line",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                    null, null);
            if (result == JOptionPane.OK_OPTION) {
                String lineName = (String) comboBox.getSelectedItem();
                List<Object> ids = this.tableAndLocation.getListTableSelectedValue("id");
                this.tableAndLocation.update(
                        RequestParam.builder().addParam("lName", lineName),
                        JsonBodyAPI.builder().put("ids", ids));
            }
        });
        PopupMenu popupMenu = this.tableAndLocation.getMenu();
        popupMenu.addItemMenu("New PC", (e) -> {
            String input = JOptionPane.showInputDialog("input");
            if (input == null) {
                return;
            }
            this.tableAndLocation.addNew(JsonBodyAPI.builder().put("name", input));
        });
        this.pnUp.add(tableAndLocation);
        this.tableAndLocation.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnUp = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnUp.setLayout(new javax.swing.BoxLayout(pnUp, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnUp, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnUp, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnUp;
    // End of variables declaration//GEN-END:variables

    public void display() {
        this.tableAndLocation.update();
        display("Manage pc");
    }
}
