/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec02.view;

import com.tec02.common.JOptionUtil;
import com.tec02.common.Keyword;
import com.tec02.API.APIController;
import com.tec02.Jmodel.Component.PopupMenu;
import com.tec02.gui.frameGui.AbsDisplayAble;
import com.tec02.gui.panelGui.TableAndLocation;
import com.tec02.common.PropertiesModel;
import com.tec02.gui.panelGui.UploadFileProgramPanel;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class ManageFileProgram extends AbsDisplayAble {

    private final TableAndLocation tableAndLocation;
    private final APIController api;
    private final UploadFileProgramPanel fileProgramPanel;

    /**
     * Creates new form ManageFgroup
     */
    public ManageFileProgram() {
        initComponents();
        this.api = APIController.getInstance();
        this.fileProgramPanel = new UploadFileProgramPanel(api);
        this.tableAndLocation = new TableAndLocation(api);
        this.tableAndLocation.setUrlAdd(PropertiesModel.getConfig(Keyword.Url.FileProgram.POST));
        this.tableAndLocation.setUrlGet(PropertiesModel.getConfig(Keyword.Url.FileProgram.GET_LIST));
        this.tableAndLocation.setUrlDelete(PropertiesModel.getConfig(Keyword.Url.FileProgram.DELETE));
        this.tableAndLocation.addColoumn(List.of(Keyword.ID, Keyword.NAME,Keyword.DESCRIPTION ));
        this.tableAndLocation.setDoubleClickAction((input) -> {
            showFileProgram();
        });
        PopupMenu selectedMenu = this.tableAndLocation.getSelectedMenu();
        selectedMenu.addItemMenu("View", (e) -> {
            showFileProgram();
        });
        selectedMenu.addItemMenu("Delete", (e) -> {
            this.tableAndLocation.deleteSeleled();
            this.fileProgramPanel.clear();
        });
        PopupMenu popupMenu = this.tableAndLocation.getMenu();
        popupMenu.addItemMenu("New", (e) -> {
            String pName = this.tableAndLocation.getProductSelection();
            String sName = this.tableAndLocation.getStationSelection();
            String lName = this.tableAndLocation.getLineSelection();
            this.fileProgramPanel.clear();
            this.fileProgramPanel.setFileInfo(pName, sName, lName, null, null);
            JOptionUtil.showObject(this.fileProgramPanel, "File viewer");
            this.tableAndLocation.find();
        });
        this.pnl.add(this.tableAndLocation);
        this.tableAndLocation.find();
    }

    public void showFileProgram() {
        Object fileProgramId = this.tableAndLocation.getTableSelectedValue(Keyword.ID);
        if (fileProgramId == null) {
            return;
        }
        String name = this.tableAndLocation.getTableSelectedValueT(Keyword.NAME);
        String pName = this.tableAndLocation.getProductSelection();
        String sName = this.tableAndLocation.getStationSelection();
        String lName = this.tableAndLocation.getLineSelection();
        this.fileProgramPanel.clear();
        this.fileProgramPanel.setFileInfo(pName, sName, lName, fileProgramId, name);
        JOptionUtil.showObject(this.fileProgramPanel, "File viewer");
        this.tableAndLocation.find();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl.setBackground(new java.awt.Color(204, 255, 255));
        pnl.setLayout(new javax.swing.BoxLayout(pnl, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JPanel pnl;
    // End of variables declaration                   

    public void display() {
        display("Manager file Program");
        this.tableAndLocation.update();
    }
}
